# Generated by Django 4.2.10 on 2024-03-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orderHelper", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(default="NoParticipantName", max_length=50),
                ),
                ("userName", models.CharField(max_length=100)),
                ("orderName", models.CharField(default="NoOrderName", max_length=100)),
                ("orderNum", models.IntegerField(default=1)),
                ("price", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "tb_participant",
            },
        ),
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("groupName", models.CharField(default="NoGroupName", max_length=100)),
            ],
            options={
                "db_table": "user_group",
            },
        ),
        migrations.RemoveField(
            model_name="order",
            name="orderManu",
        ),
        migrations.RemoveField(
            model_name="order",
            name="orderRaiser",
        ),
        migrations.AddField(
            model_name="order",
            name="orderGroupName",
            field=models.CharField(default="NoGroupName", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="orderMenu",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="orderPrice",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="orderRaiserID",
            field=models.CharField(default="NoRaiserID", max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="orderRaiserName",
            field=models.CharField(default="NoRaiserName", max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="orderState",
            field=models.CharField(default="existing", max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="orderShop",
            field=models.CharField(default="NoShopName", max_length=100),
        ),
        migrations.AlterModelTable(
            name="order",
            table="tb_order",
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(default="NoUserID", max_length=50)),
                ("userName", models.CharField(default="NoUserName", max_length=100)),
                (
                    "groups",
                    models.ManyToManyField(
                        related_name="user_groups", to="orderHelper.usergroup"
                    ),
                ),
            ],
            options={
                "db_table": "user_profile",
            },
        ),
        migrations.AddField(
            model_name="usergroup",
            name="members",
            field=models.ManyToManyField(
                related_name="group_members", to="orderHelper.userprofile"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="orderParticipant",
            field=models.ManyToManyField(to="orderHelper.participant"),
        ),
    ]
