# Generated by Django 4.2.10 on 2024-03-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orderHelper", "0002_participant_usergroup_remove_order_ordermanu_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="userState",
            field=models.CharField(default="initial_state", max_length=100),
        ),
    ]
