# Generated by Django 4.2.11 on 2024-03-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderHelper', '0003_userprofile_userstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='userName',
            field=models.CharField(default='NoParticipantName', max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user_id',
            field=models.CharField(default='NoParticipantID', max_length=50),
        ),
    ]
